[2024-10-04T11:21:08.109+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-04T11:21:08.135+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_API_DATA.test manual__2024-10-04T11:20:56.678341+00:00 [queued]>
[2024-10-04T11:21:08.151+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_API_DATA.test manual__2024-10-04T11:20:56.678341+00:00 [queued]>
[2024-10-04T11:21:08.152+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-04T11:21:08.178+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): test> on 2024-10-04 11:20:56.678341+00:00
[2024-10-04T11:21:08.206+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=429) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-04T11:21:08.209+0000] {standard_task_runner.py:72} INFO - Started process 432 to run task
[2024-10-04T11:21:08.209+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ETL_API_DATA', 'test', 'manual__2024-10-04T11:20:56.678341+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/Extract_api_data.py', '--cfg-path', '/tmp/tmp6s4jhx11']
[2024-10-04T11:21:08.210+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask test
[2024-10-04T11:21:08.282+0000] {task_command.py:467} INFO - Running <TaskInstance: ETL_API_DATA.test manual__2024-10-04T11:20:56.678341+00:00 [running]> on host ec2f9bdc71d6
[2024-10-04T11:21:08.387+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_API_DATA' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T11:20:56.678341+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T11:20:56.678341+00:00'
[2024-10-04T11:21:08.390+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-04T11:21:08.391+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-04T11:21:08.392+0000] {logging_mixin.py:190} INFO - Current task name:test state:running start_date:2024-10-04 11:21:08.136469+00:00
[2024-10-04T11:21:08.393+0000] {logging_mixin.py:190} INFO - Dag name:ETL_API_DATA and current dag run status:running
[2024-10-04T11:21:08.393+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-04T11:21:08.395+0000] {logging_mixin.py:190} INFO - vault address is http://192.168.1.195:8200 and *** is ***
[2024-10-04T11:21:08.396+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-04T11:21:08.411+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-04T11:21:08.412+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=ETL_API_DATA, task_id=test, run_id=manual__2024-10-04T11:20:56.678341+00:00, execution_date=20241004T112056, start_date=20241004T112108, end_date=20241004T112108
[2024-10-04T11:21:08.431+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-10-04T11:21:08.432+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-10-04T11:21:08.433+0000] {logging_mixin.py:190} INFO - Dag name:ETL_API_DATA queued_at:2024-10-04 11:20:57.131138+00:00
[2024-10-04T11:21:08.434+0000] {logging_mixin.py:190} INFO - Task hostname:ec2f9bdc71d6 operator:PythonOperator
[2024-10-04T11:21:08.467+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-04T11:21:08.486+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-04T11:21:08.492+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
